### PR TITLE
export: fixes select all records problem

### LINKED ISSUE #538: Select-all export problem
When using facets to filter results and then selecting all search results there seems to still be a problem @ioannistsanaktsidis 

screen shot 2015-11-20 at 6 07 48 pm

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Closes #538.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

File: inspire/base/static/js/search/search_results.js [hunk 1]
```diff
@@ -95,6 +94,7 @@ define(
       }
 
       this.onExportSelectAll = function(ev) {
+        var minimum_page_limit = $("#select-numpages option:selected").text();
```
Comment (jmartinm) [inline inspire/base/static/js/search/search_results.js]: As it is a dropdown, doesn't it work with:

```
var minimum_page_limit = $("#select-numpages").val();
```
?

Comment (ioannistsanaktsidis) [inline inspire/base/static/js/search/search_results.js]: No, but it works like this var minimum_page_limit = $("#select-numpages
option:selected").val(); . Should we keep .text() or .val() ?


2015-11-24 11:58 GMT+01:00 Javier Martin Montull <notifications@github.com>:
